# Generated by Django 4.2.1 on 2023-07-15 19:41

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True, verbose_name='Slug')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Course Overview')),
                ('about_guru', models.TextField(blank=True, null=True, verbose_name='About Guru')),
                ('course_icon', models.ImageField(upload_to='images/courses/', validators=[course.models.validate_course_icon_size])),
                ('course_banner', models.ImageField(upload_to='images/courses/', validators=[course.models.validate_course_banner_size])),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Level Name')),
                ('description', models.CharField(default='Every Grandmaster Was A Novice.', max_length=100, verbose_name='Level Description')),
                ('num_classes', models.IntegerField(blank=True, null=True, verbose_name='Number Of Classes')),
                ('frequency', models.IntegerField(blank=True, null=True, verbose_name='Frequency (days/week)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration of course (in weeks)')),
                ('starts_from', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Starts From')),
            ],
            options={
                'verbose_name': 'Course Level',
                'verbose_name_plural': 'Course Levels',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Description')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (Discounted)')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Price')),
                ('count_sibling', models.BooleanField(default=False, verbose_name='Count Number of Siblings or Not?')),
            ],
            options={
                'verbose_name': 'Course Plans',
                'verbose_name_plural': 'Course Plans',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=100, verbose_name='Schedule Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('total_num_of_seats', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Total Number of seats')),
                ('seats_occupied', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Number of seats occupied')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3, verbose_name='Day')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time ')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timing', to='course.schedule')),
            ],
        ),
    ]
