# Generated by Django 4.2.1 on 2023-06-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Course Overview')),
            ],
        ),
    ]
