# Generated by Django 4.2.1 on 2023-09-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guru.guru', verbose_name='Guru'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.plans', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='to_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='course.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='levels',
            name='to_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_levels', to='course.course'),
        ),
        migrations.AddField(
            model_name='historicalscheduletiming',
            name='batch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.schedule'),
        ),
    ]
