# Generated by Django 4.2.1 on 2023-06-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Course Overview'),
        ),
    ]
