# Generated by Django 4.2.1 on 2023-08-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='count_sibling',
        ),
        migrations.AlterField(
            model_name='plans',
            name='name',
            field=models.CharField(choices=[('One-on-One', 'One-on-One'), ('Batch', 'Batch'), ('Siblings', 'Siblings'), ('Demo Class', 'Demo Class')], max_length=100, verbose_name='Plan Name'),
        ),
    ]
