# Generated by Django 4.2.1 on 2023-06-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Level Name')),
                ('num_classes', models.IntegerField(blank=True, null=True, verbose_name='Number Of Classes')),
                ('frequency', models.IntegerField(blank=True, null=True, verbose_name='Frequency (days/week)')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration of course (in weeks)')),
                ('to_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
