# Generated by Django 4.2.1 on 2023-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_plans_count_sibling_alter_plans_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='original_price',
        ),
        migrations.AddField(
            model_name='plans',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Discont Per cent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
