# Generated by Django 4.2.1 on 2023-09-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='Title of the course', max_length=150, verbose_name='Course Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='title',
            field=models.CharField(default='Title of the course', max_length=150, verbose_name='Course Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Course Name'),
        ),
    ]
