# Generated by Django 4.2.1 on 2023-08-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_plans_actual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='to_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='course.course', verbose_name='Course'),
        ),
    ]
