# Generated by Django 4.2.1 on 2023-06-26 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_levels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='levels',
            options={'verbose_name': 'Course Level', 'verbose_name_plural': 'Course Levels'},
        ),
        migrations.AddField(
            model_name='levels',
            name='description',
            field=models.CharField(default='Every Grandmaster Was A Novice.', max_length=100, verbose_name='Level Description'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='to_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_levels', to='course.course'),
        ),
    ]
