# Generated by Django 4.2.1 on 2023-09-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_title_alter_historicalcourse_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_banner_url',
            field=models.URLField(blank=True, null=True, verbose_name='Course Banner URL'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='course_banner_url',
            field=models.URLField(blank=True, null=True, verbose_name='Course Banner URL'),
        ),
    ]
