# Generated by Django 4.2.1 on 2023-06-27 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_levels_starts_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Plan Name')),
                ('description', models.CharField(max_length=100, verbose_name='Plan Description')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (Discounted)')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Price')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_plans', to='course.levels')),
            ],
            options={
                'verbose_name': 'Course Plans',
                'verbose_name_plural': 'Course Plans',
            },
        ),
    ]
