# Generated by Django 4.2.1 on 2023-08-20 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_is_active_levels_is_active_schedule_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletiming',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AddField(
            model_name='scheduletiming',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
