# Generated by Django 4.2.1 on 2023-06-27 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='to_level',
        ),
    ]
