# Generated by Django 4.2.1 on 2023-09-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_historicalplans_course_plans_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplans',
            name='name',
            field=models.CharField(choices=[('One-on-One', 'One-on-One'), ('Batch', 'Batch'), ('Group Sessions', 'Group Sessions'), ('Siblings', 'Siblings'), ('Demo Class', 'Demo Class')], max_length=100, verbose_name='Plan Name'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='name',
            field=models.CharField(choices=[('One-on-One', 'One-on-One'), ('Batch', 'Batch'), ('Group Sessions', 'Group Sessions'), ('Siblings', 'Siblings'), ('Demo Class', 'Demo Class')], max_length=100, verbose_name='Plan Name'),
        ),
    ]
