# Generated by Django 4.2.1 on 2023-09-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_historicalplans_name_alter_plans_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallevels',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='historicallevels',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='historicallevels',
            name='num_classes',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='num_classes',
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration of course (in weeks)'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='frequency',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frequency (days/week)'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='num_classes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number Of Classes'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration of course (in weeks)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='frequency',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frequency (days/week)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='num_classes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number Of Classes'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_plans', to='course.course'),
        ),
    ]
