# Generated by Django 4.2.1 on 2023-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_historicallevels_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallevels',
            name='decrement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Decrease price by: '),
        ),
        migrations.AddField(
            model_name='historicallevels',
            name='increment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Increase price by: '),
        ),
        migrations.AddField(
            model_name='levels',
            name='decrement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Decrease price by: '),
        ),
        migrations.AddField(
            model_name='levels',
            name='increment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Increase price by: '),
        ),
    ]
