# Generated by Django 4.2.1 on 2023-06-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_plans_count_sibling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Description'),
        ),
    ]
