# Generated by Django 4.2.1 on 2023-08-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_historicalscheduletiming_historicalschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplans',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discont per cent'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discont per cent'),
        ),
    ]
