# Generated by Django 4.2.1 on 2023-06-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_plans_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('total_num_of_seats', models.IntegerField(verbose_name='Total Number of seats')),
                ('steats_occupied', models.IntegerField(verbose_name='Number of seats occupied')),
            ],
        ),
    ]
