# Generated by Django 4.2.1 on 2023-09-13 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_historicallevels_decrement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallevels',
            name='starts_from',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='starts_from',
        ),
    ]
