# Generated by Django 4.2.1 on 2023-09-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_historicallevels_starts_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='about_guru',
        ),
        migrations.RemoveField(
            model_name='historicalcourse',
            name='about_guru',
        ),
    ]
