# Generated by Django 4.2.1 on 2023-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='steats_occupied',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Number of seats occupied'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='total_num_of_seats',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Total Number of seats'),
        ),
    ]
