# Generated by Django 4.2.1 on 2023-06-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_batch_steats_occupied_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='steats_occupied',
            new_name='seats_occupied',
        ),
    ]
