# Generated by Django 4.2.1 on 2023-06-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_batch_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='seats_occupied',
        ),
    ]
