# Generated by Django 4.2.1 on 2023-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_batch_seats_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='seats_occupied',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=3, verbose_name='Number of seats occupied'),
            preserve_default=False,
        ),
    ]
