# Generated by Django 4.2.1 on 2023-09-19 17:12

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_historicallevels_decrement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/courses/', validators=[course.models.validate_course_icon_size]),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='course_icon',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[course.models.validate_course_icon_size]),
        ),
    ]
