# Generated by Django 4.2.1 on 2023-06-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_batchtiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtiming',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchtiming',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='batchtiming',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='batchtiming',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
    ]
