# Generated by Django 4.2.1 on 2023-06-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_batch_batch_name_alter_batchtiming_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_icon',
            field=models.ImageField(default='Hello', upload_to='images/courses/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(max_length=100, verbose_name='Batch Name'),
        ),
        migrations.AlterField(
            model_name='batchtiming',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timing', to='course.batch'),
        ),
        migrations.AlterField(
            model_name='batchtiming',
            name='day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3, verbose_name='Day'),
        ),
    ]
