# Generated by Django 4.2.1 on 2023-09-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_remove_historicalschedule_to_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='to_course_level',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.levels', verbose_name='Course Level'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='to_course_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_schedules', to='course.levels', verbose_name='Course Level'),
        ),
    ]
