# Generated by Django 4.2.1 on 2023-06-28 18:13

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_course_course_icon_alter_batch_batch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_icon',
            field=models.ImageField(upload_to='images/courses/', validators=[course.models.validate_course_icon_size]),
        ),
    ]
