# Generated by Django 4.2.1 on 2023-09-23 17:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0021_alter_historicalschedule_to_course_level_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalScheduleTiming',
            new_name='HistoricalSession',
        ),
        migrations.RenameModel(
            old_name='ScheduleTiming',
            new_name='Session',
        ),
    ]
