# Generated by Django 4.2.1 on 2023-06-28 18:23

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_alter_course_course_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_banner',
            field=models.ImageField(default='Banner', upload_to='images/courses/', validators=[course.models.validate_course_banner_size]),
            preserve_default=False,
        ),
    ]
