# Generated by Django 4.2.1 on 2023-06-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_course_course_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='to_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course', verbose_name='Course'),
        ),
    ]
