# Generated by Django 4.2.1 on 2023-06-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_kid_batch_enrolled_in'),
        ('purchase', '0008_alter_purchase_batch_alter_purchase_course_level'),
        ('course', '0023_batch_to_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batch',
            new_name='Schedule',
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
    ]
