# Generated by Django 4.2.1 on 2023-09-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_remove_historicalschedule_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallevels',
            name='num_classes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number Of Classes/Sessions'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='num_classes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number Of Classes/Sessions'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='to_course_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_level_schedules', to='course.levels', verbose_name='Course Level'),
        ),
    ]
