# Generated by Django 4.2.1 on 2023-06-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_rename_batch_schedule_alter_schedule_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatchTiming',
            new_name='ScheduleTiming',
        ),
    ]
