# Generated by Django 4.2.1 on 2023-10-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_historicalschedule_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallevels',
            name='tier',
            field=models.CharField(choices=[('TIER_1', 'TIER_1'), ('TIER_2', 'TIER_2'), ('TIER_3', 'TIER_3'), ('TIER_4', 'TIER_4'), ('TIER_5', 'TIER_5')], default='TIER_1', help_text="Required for the server. (Use 'TIER_1' for beginner, 'TIER_2' for intermediate and so on.)", max_length=100, verbose_name='Tier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='levels',
            name='tier',
            field=models.CharField(choices=[('TIER_1', 'TIER_1'), ('TIER_2', 'TIER_2'), ('TIER_3', 'TIER_3'), ('TIER_4', 'TIER_4'), ('TIER_5', 'TIER_5')], default='TIER_1', help_text="Required for the server. (Use 'TIER_1' for beginner, 'TIER_2' for intermediate and so on.)", max_length=100, verbose_name='Tier'),
            preserve_default=False,
        ),
    ]
