# Generated by Django 4.2.1 on 2023-06-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_schedule_plans_schedule_guru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='Plans',
            new_name='plans',
        ),
    ]
