# Generated by Django 4.2.1 on 2023-06-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_rename_plans_schedule_plans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='plans',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='batch_name',
            new_name='schedule_name',
        ),
    ]
