# Generated by Django 4.2.1 on 2023-06-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '__first__'),
        ('course', '0028_rename_plans_schedule_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guru.guru', verbose_name='Guru'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.plans', verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_name',
            field=models.CharField(max_length=100, verbose_name='Schedule Name'),
        ),
    ]
