# Generated by Django 4.2.1 on 2023-06-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQs',
        ),
    ]
