# Generated by Django 4.2.1 on 2023-09-11 10:56

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPurchase',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (Purchased With )')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Payment Status')),
                ('payment_method', models.CharField(blank=True, choices=[('Free Purchase', 'Free Purchase'), ('Razorpay', 'Razorpay'), ('Cashfree', 'Cashfree')], max_length=50, null=True, verbose_name='Payment Method')),
                ('order_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Order ID')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment ID')),
                ('booking_id', models.CharField(max_length=120, verbose_name='Booking ID')),
                ('order_signature', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razorpay Signature')),
                ('purchased_at', models.DateTimeField(blank=True, editable=False, verbose_name='Purchased At')),
                ('last_modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last Modified At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Purchase',
                'verbose_name_plural': 'historical Purchases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (Purchased With )')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Payment Status')),
                ('payment_method', models.CharField(blank=True, choices=[('Free Purchase', 'Free Purchase'), ('Razorpay', 'Razorpay'), ('Cashfree', 'Cashfree')], max_length=50, null=True, verbose_name='Payment Method')),
                ('order_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Order ID')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment ID')),
                ('booking_id', models.CharField(max_length=120, verbose_name='Booking ID')),
                ('order_signature', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razorpay Signature')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Purchased At')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='PurchaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('session_status', models.CharField(blank=True, choices=[('INCOMPLETE', 'INCOMPLETE'), ('COMPLETED', 'COMPLETED')], default='INCOMPLETE', help_text="'COMPLETED' refers that user made purchase with this session. Purchase may be failed or succeeded.", max_length=20, null=True)),
                ('course_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('level_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.levels')),
                ('plan_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.plans')),
            ],
            options={
                'verbose_name': 'Purchase Session',
                'verbose_name_plural': 'Purchase Sessions',
            },
        ),
    ]
