# Generated by Django 4.2.1 on 2023-07-15 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (Purchased With )')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Payment Status')),
                ('order_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Order ID')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment ID')),
                ('order_signature', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razorpay Signature')),
                ('course_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.levels', verbose_name='Course Level Selected')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
    ]
