# Generated by Django 4.2.1 on 2023-07-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='kids_selected',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_purchases', to='user.kid'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='plan_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.plans', verbose_name='Plan Selected'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.schedule', verbose_name='Batch Enrolled in'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_purchase', to=settings.AUTH_USER_MODEL, verbose_name='Purchased By'),
        ),
    ]
