# Generated by Django 4.2.1 on 2023-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='dummy',
            field=models.JSONField(blank=True, null=True, verbose_name='Dummy'),
        ),
    ]
