# Generated by Django 4.2.1 on 2023-08-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Razorpay', 'Razorpay')], max_length=10, null=True, verbose_name='Payment Method'),
        ),
    ]
