# Generated by Django 4.2.1 on 2023-09-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpurchase',
            old_name='payment_method',
            new_name='payment_platform',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='payment_method',
            new_name='payment_platform',
        ),
    ]
