# Generated by Django 4.2.1 on 2023-09-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_rename_payment_method_historicalpurchase_payment_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method'),
        ),
    ]
