# Generated by Django 4.2.1 on 2023-08-20 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_historicaluser_historicalotp_historicalkid'),
        ('course', '0010_historicalscheduletiming_historicalschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0004_purchase_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='kids_selected',
            field=models.ManyToManyField(blank=True, related_name='my_purchases', to='user.kid'),
        ),
        migrations.CreateModel(
            name='HistoricalPurchase',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (Purchased With )')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Payment Status')),
                ('payment_method', models.CharField(blank=True, choices=[('Razorpay', 'Razorpay')], max_length=10, null=True, verbose_name='Payment Method')),
                ('order_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Order ID')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment ID')),
                ('order_signature', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razorpay Signature')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course_level', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.levels', verbose_name='Course Level Selected')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan_selected', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.plans', verbose_name='Plan Selected')),
                ('schedule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.schedule', verbose_name='Batch Enrolled in')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Purchased By')),
            ],
            options={
                'verbose_name': 'historical Purchase',
                'verbose_name_plural': 'historical Purchases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
