# Generated by Django 4.2.1 on 2023-09-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_historicalpurchase_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchase',
            name='payment_method',
            field=models.JSONField(blank=True, null=True, verbose_name='Payment Method (JSON)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.JSONField(blank=True, null=True, verbose_name='Payment Method (JSON)'),
        ),
    ]
