# Generated by Django 4.2.1 on 2023-06-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_batch_to_course'),
        ('purchase', '0005_remove_purchase_dummy_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course', verbose_name='Batch Enrolled in'),
        ),
    ]
