# Generated by Django 4.2.1 on 2023-08-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_purchase_kids_selected_historicalpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Free Purchase', 'Free Purchase'), ('Razorpay', 'Razorpay')], max_length=50, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Free Purchase', 'Free Purchase'), ('Razorpay', 'Razorpay')], max_length=50, null=True, verbose_name='Payment Method'),
        ),
    ]
