# Generated by Django 4.2.1 on 2023-09-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_alter_historicalschedule_to_course_level_and_more'),
        ('purchase', '0005_alter_historicalpurchase_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='course_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_purchase', to='course.levels', verbose_name='Course Level Selected'),
        ),
    ]
