# Generated by Django 4.2.1 on 2023-06-30 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0023_batch_to_course'),
        ('purchase', '0006_purchase_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='course_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.levels', verbose_name='Purchased By'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='plan_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.plans', verbose_name='Plan Selected'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=10, verbose_name='Price (Purchased With )'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_purchase', to=settings.AUTH_USER_MODEL, verbose_name='Purchased By'),
        ),
    ]
