# Generated by Django 4.2.1 on 2023-08-24 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_historicalpurchase_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Purchased At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Purchased At'),
            preserve_default=False,
        ),
    ]
