# Generated by Django 4.2.1 on 2023-08-24 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_historicalpurchase_purchased_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='last_modified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Last Modified At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='purchased_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Purchased At'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Purchased At'),
        ),
    ]
