# Generated by Django 4.2.1 on 2023-06-30 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_batch_to_course'),
        ('purchase', '0007_purchase_course_level_purchase_plan_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.batch', verbose_name='Batch Enrolled in'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='course_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.levels', verbose_name='Course Level Selected'),
        ),
    ]
