# Generated by Django 4.2.1 on 2023-09-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_alter_historicalpurchase_purchase_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='purchase.purchasesession', verbose_name='Purchase Session'),
        ),
    ]
