# Generated by Django 4.2.1 on 2023-07-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_kid_batch_enrolled_in'),
        ('purchase', '0008_alter_purchase_batch_alter_purchase_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='kids_selected',
            field=models.ManyToManyField(related_name='my_purchases', to='user.kid'),
        ),
    ]
