# Generated by Django 4.2.1 on 2023-09-01 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_historicalpurchase_last_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='booking_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Booking ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='booking_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Booking ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Free Purchase', 'Free Purchase'), ('Razorpay', 'Razorpay'), ('Cashfree', 'Cashfree')], max_length=50, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Free Purchase', 'Free Purchase'), ('Razorpay', 'Razorpay'), ('Cashfree', 'Cashfree')], max_length=50, null=True, verbose_name='Payment Method'),
        ),
    ]
