# Generated by Django 4.2.1 on 2023-09-06 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0012_remove_historicalschedule_end_date_and_more'),
        ('purchase', '0009_historicalpurchase_booking_id_purchase_booking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('session_status', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('PURCHASED', 'PURCHASED')], default='ONGOING', max_length=20, null=True)),
                ('course_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('level_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.levels')),
                ('plan_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.plans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Session',
                'verbose_name_plural': 'Purchase Sessions',
            },
        ),
    ]
