# Generated by Django 4.2.1 on 2023-07-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_kid_batch_enrolled_in'),
        ('purchase', '0009_purchase_kids_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='batch',
            new_name='schedule',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='kids_selected',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_purchases', to='user.kid'),
        ),
    ]
