# Generated by Django 4.2.1 on 2023-07-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_purchase_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Order ID'),
        ),
    ]
