# Generated by Django 4.2.1 on 2023-07-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_purchase_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_signature',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razorpay Signature'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment ID'),
        ),
    ]
