# Generated by Django 4.2.1 on 2023-08-18 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_plans_actual_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=0, default=1, help_text='Pick between 1 to 5', max_digits=1, validators=[home.models.validate_rating])),
                ('content', models.TextField(max_length=150, verbose_name='Content')),
                ('review_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Review given by')),
                ('to_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_reviews', to='course.course', verbose_name='Course')),
            ],
        ),
    ]
