# Generated by Django 4.2.1 on 2023-06-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_course_course_banner'),
        ('home', '0002_alter_faqs_options_faqs_faq_for_alter_faqs_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='faq_for',
            field=models.ForeignKey(blank=True, default='Default Course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_faqs', to='course.course', verbose_name='FAQ For'),
        ),
    ]
