# Generated by Django 4.2.1 on 2023-09-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreview',
            name='review_for',
            field=models.CharField(blank=True, choices=[('GURUFA', 'GURUFA'), ('COURSE', 'COURSE')], max_length=100, null=True, verbose_name='Review is for?'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_for',
            field=models.CharField(blank=True, choices=[('GURUFA', 'GURUFA'), ('COURSE', 'COURSE')], max_length=100, null=True, verbose_name='Review is for?'),
        ),
    ]
