# Generated by Django 4.2.1 on 2023-09-13 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_schedule_guru'),
        ('home', '0003_historicalreview_review_for_review_review_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='to_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_faqs', to='course.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='historicalfaqs',
            name='to_course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='faq_for',
            field=models.CharField(blank=True, choices=[('GURUFA', 'GURUFA'), ('COURSE', 'COURSE')], max_length=100, null=True, verbose_name='FAQ is for?'),
        ),
        migrations.AlterField(
            model_name='historicalfaqs',
            name='faq_for',
            field=models.CharField(blank=True, choices=[('GURUFA', 'GURUFA'), ('COURSE', 'COURSE')], max_length=100, null=True, verbose_name='FAQ is for?'),
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='content',
            field=models.TextField(max_length=250, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=250, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
