# Generated by Django 4.2.1 on 2023-06-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_course_course_banner'),
        ('home', '0003_alter_faqs_faq_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='faq_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_faqs', to='course.course', verbose_name='FAQ For'),
        ),
    ]
