# Generated by Django 4.2.1 on 2023-09-14 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_historicallevels_decrement_and_more'),
        ('home', '0004_faqs_to_course_historicalfaqs_to_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='faq_for',
            field=models.CharField(blank=True, choices=[('GURUFA', 'GURUFA'), ('COURSE', 'COURSE')], help_text='Leave blank, if course is not chosen.', max_length=100, null=True, verbose_name='FAQ is for?'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='to_course',
            field=models.ForeignKey(blank=True, help_text='Leave blank, if FAQ is not for any Course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_faqs', to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='historicalfaqs',
            name='faq_for',
            field=models.CharField(blank=True, choices=[('GURUFA', 'GURUFA'), ('COURSE', 'COURSE')], help_text='Leave blank, if course is not chosen.', max_length=100, null=True, verbose_name='FAQ is for?'),
        ),
        migrations.AlterField(
            model_name='historicalfaqs',
            name='to_course',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Leave blank, if FAQ is not for any Course.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='review_for',
            field=models.CharField(blank=True, choices=[('GURUFA', 'GURUFA'), ('COURSE', 'COURSE')], help_text='Leave blank, if course is not chosen.', max_length=100, null=True, verbose_name='Review is for?'),
        ),
        migrations.AlterField(
            model_name='historicalreview',
            name='to_course',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Leave blank, if Review is not for any Course.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_for',
            field=models.CharField(blank=True, choices=[('GURUFA', 'GURUFA'), ('COURSE', 'COURSE')], help_text='Leave blank, if course is not chosen.', max_length=100, null=True, verbose_name='Review is for?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='to_course',
            field=models.ForeignKey(blank=True, help_text='Leave blank, if Review is not for any Course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_reviews', to='course.course', verbose_name='Course'),
        ),
    ]
