# Generated by Django 4.2.1 on 2023-09-14 20:43

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_faqs_faq_for_alter_faqs_to_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreview',
            name='rating',
            field=models.DecimalField(decimal_places=0, help_text='Pick between 1 to 5', max_digits=1, validators=[home.models.validate_rating]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=0, help_text='Pick between 1 to 5', max_digits=1, validators=[home.models.validate_rating]),
        ),
    ]
