# Generated by Django 4.2.1 on 2023-09-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_historicalreview_rating_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreview',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
