# Generated by Django 4.2.1 on 2023-09-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_historicalreview_content_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreview',
            name='content',
            field=models.TextField(help_text='Wrap up the review in less than 200 characters.', max_length=200, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(help_text='Wrap up the review in less than 200 characters.', max_length=200, verbose_name='Content'),
        ),
    ]
