# Generated by Django 4.2.1 on 2023-10-13 21:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_faqs_is_active_alter_historicalfaqs_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Customer Operation',
                'verbose_name_plural': 'Customer Operations',
            },
        ),
    ]
