# Generated by Django 4.2.1 on 2023-10-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_customeroperations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeroperations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
