# Generated by Django 4.2.1 on 2023-10-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_customeroperations_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeroperations',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
