# Generated by Django 4.2.1 on 2023-09-11 10:56

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeAGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number ')),
                ('yrs_experience', models.CharField(choices=[('0 Years', '0 Years'), ('1-3 Years', '1-3 Years'), ('More Than 3 Years', 'More Than 3 Years')], max_length=50, verbose_name='Years of teaching experience')),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('Chess', 'Chess'), ("Rubik's Cube", "Rubik's Cube"), ('Vedic Maths', 'Vedic Maths'), ('Yoga', 'Yoga'), ('Other', 'Other')], max_length=100, verbose_name='Skills')),
                ('other_skills', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Skills')),
            ],
            options={
                'verbose_name': 'Become A Guru Application',
                'verbose_name_plural': 'Become A Guru Applications',
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('experience', models.FloatField(default=0, verbose_name='Years Of Experience')),
            ],
            options={
                'verbose_name': 'Guru',
                'verbose_name_plural': 'Gurus',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBecomeAGuru',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number ')),
                ('yrs_experience', models.CharField(choices=[('0 Years', '0 Years'), ('1-3 Years', '1-3 Years'), ('More Than 3 Years', 'More Than 3 Years')], max_length=50, verbose_name='Years of teaching experience')),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('Chess', 'Chess'), ("Rubik's Cube", "Rubik's Cube"), ('Vedic Maths', 'Vedic Maths'), ('Yoga', 'Yoga'), ('Other', 'Other')], max_length=100, verbose_name='Skills')),
                ('other_skills', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Skills')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Become A Guru Application',
                'verbose_name_plural': 'historical Become A Guru Applications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGuru',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('experience', models.FloatField(default=0, verbose_name='Years Of Experience')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Guru',
                'verbose_name_plural': 'historical Gurus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
