# Generated by Django 4.2.1 on 2023-07-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.FloatField(default=0, verbose_name='Years Of Experience')),
            ],
            options={
                'verbose_name': 'Guru',
                'verbose_name_plural': 'Gurus',
            },
        ),
    ]
