# Generated by Django 4.2.1 on 2023-06-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guru',
            options={'verbose_name': 'Guru', 'verbose_name_plural': 'Gurus'},
        ),
    ]
