# Generated by Django 4.2.1 on 2023-08-03 10:13

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeAGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number ')),
                ('yrs_experience', models.DecimalField(decimal_places=2, max_digits=2, unique=True, verbose_name='Years of teaching experience')),
                ('skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Chess', 'Chess'), ("Rubik's Cube", "Rubik's Cube"), ('Vedic Maths', 'Vedic Maths'), ('Yoga', 'Yoga'), ('Other', 'Other')], max_length=100, verbose_name='Skills')),
            ],
            options={
                'verbose_name': 'Become A Guru Application',
                'verbose_name_plural': 'Become A Guru Applications',
            },
        ),
    ]
