# Generated by Django 4.2.1 on 2023-08-03 10:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0003_becomeaguru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomeaguru',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Chess', 'Chess'), ("Rubik's Cube", "Rubik's Cube"), ('Vedic Maths', 'Vedic Maths'), ('Yoga', 'Yoga'), ('Other', 'Other')], max_length=100, verbose_name='Skills'),
        ),
    ]
