# Generated by Django 4.2.1 on 2023-08-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0005_alter_becomeaguru_yrs_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomeaguru',
            name='yrs_experience',
            field=models.DecimalField(decimal_places=1, max_digits=3, unique=True, verbose_name='Years of teaching experience'),
        ),
    ]
