# Generated by Django 4.2.1 on 2023-08-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0006_alter_becomeaguru_yrs_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='becomeaguru',
            name='other_skills',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Skills'),
        ),
    ]
