# Generated by Django 4.2.1 on 2023-08-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0010_alter_becomeaguru_yrs_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='becomeaguru',
            name='yrs_experience',
            field=models.CharField(choices=[('0 Years', '0 Years'), ('1-3 Years', '1-3 Years'), ('More Than 3 Years', 'More Than 3 Years')], max_length=50, verbose_name='Years of teaching experience'),
        ),
    ]
