# Generated by Django 4.2.1 on 2023-07-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('auth_providers', models.CharField(choices=[('Email', 'AUTH_PROVIDER_EMAIL'), ('Google', 'AUTH_PROVIDER_GOOGLE')], default='Email', max_length=100, verbose_name='Auth Providers')),
                ('user_roles', models.CharField(choices=[('Parent', 'PARENT'), ('Guru', 'GURU')], default='Parent', max_length=100, verbose_name='User Role')),
                ('is_a_guru', models.BooleanField(default=False, verbose_name='Is A Guru?')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Phone number already being used.'}, max_length=128, region=None, unique=True, verbose_name='Phone Number ')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Phone verified')),
                ('whatsapp_update', models.BooleanField(default=False, verbose_name='Opted for WhatsApp Update')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User (Parent)',
                'verbose_name_plural': 'Users (Parent)',
            },
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_profile', models.ImageField(blank=True, null=True, upload_to='images/users/')),
                ('kid_first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('kid_last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('kid_age', models.PositiveIntegerField(default=0, verbose_name="Kid's Age (In Years)")),
                ('kid_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_kids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kid',
                'verbose_name_plural': 'Kids',
            },
        ),
    ]
