# Generated by Django 4.2.1 on 2023-06-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_batch_to_course'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='batch_enrolled_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.batch', verbose_name='Batch Enrolled in'),
        ),
    ]
