# Generated by Django 4.2.1 on 2023-10-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_historicallevels_tier_levels_tier'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='demo_courses',
            field=models.ManyToManyField(blank=True, related_name='kids_taken_demo', to='course.course', verbose_name='Demo Course Purchased'),
        ),
    ]
