# Generated by Django 4.2.1 on 2023-06-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_a_guru',
            field=models.BooleanField(default=False, verbose_name='Is A Guru?'),
        ),
    ]
