# Generated by Django 4.2.1 on 2023-06-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_batch_to_course'),
        ('user', '0002_kid_batch_enrolled_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='batch_enrolled_in',
        ),
        migrations.AddField(
            model_name='kid',
            name='batch_enrolled_in',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_batch', to='course.batch', verbose_name='Batch Enrolled in'),
        ),
    ]
