# Generated by Django 4.2.1 on 2023-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_a_guru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_profile', models.ImageField(upload_to='images/users/')),
                ('kid_first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('kid_last_name', models.CharField(max_length=150, verbose_name='Last name')),
            ],
            options={
                'verbose_name': 'Kid',
                'verbose_name_plural': 'Kids',
            },
        ),
    ]
