# Generated by Django 4.2.1 on 2023-06-12 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_kid'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='kid_age',
            field=models.PositiveIntegerField(default=0, verbose_name="Kid's Age (In Years)"),
        ),
        migrations.AddField(
            model_name='kid',
            name='kis_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
