# Generated by Django 4.2.1 on 2023-05-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_email_verified_user_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_update',
            field=models.BooleanField(default=False),
        ),
    ]
