# Generated by Django 4.2.1 on 2023-06-05 15:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_whatsapp_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Phone verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_update',
            field=models.BooleanField(default=False, verbose_name='Opted for WhatsApp Update'),
        ),
    ]
