# Generated by Django 4.2.1 on 2023-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
