# Generated by Django 4.2.1 on 2023-06-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_kid_kid_age_kid_kis_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='kis_parent',
            new_name='kid_parent',
        ),
    ]
