# Generated by Django 4.2.1 on 2023-07-26 17:59

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='kid_gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Prefer Not to Answer/State', 'PNAS')], default='Prefer Not to Answer/State', max_length=100, verbose_name="Kid's Gender"),
        ),
        migrations.AlterField(
            model_name='kid',
            name='kid_age',
            field=models.PositiveIntegerField(default=5, validators=[user.validators.validate_kids_age], verbose_name="Kid's Age (In Years)"),
        ),
        migrations.AlterField(
            model_name='kid',
            name='kid_first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='kid_last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='kid_profile',
            field=models.ImageField(blank=True, default='images/kids/kids_avatar.png', null=True, upload_to='images/kids/', verbose_name="Kid's Profile Picture"),
        ),
    ]
