# Generated by Django 4.2.1 on 2023-08-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_kid_kid_gender_alter_kid_kid_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
