# Generated by Django 4.2.1 on 2023-07-01 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_kid_batch_enrolled_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='kid_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_kids', to=settings.AUTH_USER_MODEL),
        ),
    ]
