# Generated by Django 4.2.1 on 2023-08-21 11:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_historicaluser_historicalotp_historicalkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None, verbose_name='Phone Number '),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Phone Number '),
        ),
    ]
