# Generated by Django 4.2.1 on 2023-08-28 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_historicalplans_discount_percent_and_more'),
        ('user', '0010_alter_historicaluser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkid',
            name='demo_courses',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course.course'),
        ),
        migrations.AddField(
            model_name='kid',
            name='demo_courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kids_taken_demo', to='course.course'),
        ),
    ]
