# Generated by Django 4.2.1 on 2023-08-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_historicalplans_discount_percent_and_more'),
        ('user', '0011_historicalkid_demo_courses_kid_demo_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkid',
            name='demo_courses',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='demo_courses',
        ),
        migrations.AddField(
            model_name='kid',
            name='demo_courses',
            field=models.ManyToManyField(related_name='kids_taken_demo', to='course.course'),
        ),
    ]
