# Generated by Django 4.2.1 on 2023-08-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_historicalplans_discount_percent_and_more'),
        ('user', '0012_remove_historicalkid_demo_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='demo_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='kids_taken_demo', to='course.course', verbose_name='Demo Course Purchased'),
        ),
    ]
